name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pyautogui
      - name: Run unit and integration tests
        run: |
          mkdir -p reports
          xvfb-run -a python -m pytest -vv tests origo3d/tests/integration qa ui_tests \
            --junitxml=reports/tests.xml \
            --cov=. --cov-report=xml:reports/coverage.xml
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
